// Code_samples/Angular/app.component.ts
import { Component } from '@angular/core';
import { OpenApiService } from './services/open-api.service';
import { Dataset } from './models/dataset.model';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'openApiClient';
  sourceId = 'nokkel';
  tableId = 1;
  data!: Observable<Dataset>;

  constructor(
    private openApiService: OpenApiService,
  ) {}

  sources = this.openApiService.getSources()
  tables = this.openApiService.getTables(this.sourceId)
  metadata = this.openApiService.getMetadata(this.sourceId, this.tableId)
  dimensions = this.openApiService.getDimensions(this.sourceId, this.tableId)
  flags = this.openApiService.getFlags(this.sourceId, this.tableId)

  query = this.openApiService.getQuery(this.sourceId, this.tableId).subscribe((query) => {
    this.data = this.openApiService.getData(this.sourceId, this.tableId, query)
  })
}

// Code_samples/React/fhi-open-api-client/src/App.js
import './App.css';
import {useEffect, useState} from "react";
import {getData, getQuery, getSources, getTables} from './api'

function App() {
  const sourceId = 'nokkel';
  const tableId = 1;


  const [sources, setSources] = useState([]);
  const [tables, setTables] = useState([]);
  const [modifiedTables, setModifiedTables] = useState([]);
  const [metadata, setMetadata] = useState([]);
  const [flags, setFlags] = useState([]);
  const [dimensions, setDimensions] = useState([]);
  const [query, setQuery] = useState([]);
  const [data, setData] = useState('');

  useEffect(() => {
    let mounted = true;
    getSources()
      .then(items => {
        if (mounted) {
          setSources(items)
        }
      });
    getTables(sourceId)
      .then(items => {
        if (mounted) {
          setTables(items)
        }
      });
    getQuery(sourceId, tableId)
      .then(response => {
        if (mounted) {
          getData(sourceId, tableId, response)
            .then(response => {
              const subset = `${JSON.stringify(response).substring(0, 1000)}...`
              setData(subset)
            })
          setQuery(response)
        }
      })
    return () => mounted = false;
  }, []);

  return (
    <div className="App">
      <div>
        <h2>Sources</h2>
        <ul>
          {sources.map(item => (<li key={item.title}>{item.title}</li>))}
        </ul>
        <h2>Query</h2>
        <pre>{JSON.stringify(query)}</pre>
        <h2>Data</h2>
        <pre>{data}</pre>
      </div>
    </div>
  );
}

export default App;
