// Code_samples/angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { OpenApiService } from './open-api.service';
import { SourceInfo } from './models/sourceInfo.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  title = 'openApiClient';
  sourceId = 'nokkel';
  tableId = 2;
  data: any;
  sources: SourceInfo[] | undefined
  tables: any;
  metadata: any;
  dimensions: any;
  flags: any;

  constructor(
    private openApiService: OpenApiService,
  ) {}

  ngOnInit(): void {
    this.openApiService.getSources().subscribe((sourceInfo) => this.sources = sourceInfo)
    // this.openApiService.getTables(this.sourceId).subscribe((tables) => this.tables = tables)
    // this.openApiService.getMetadata(this.sourceId, this.tableId).subscribe((metadata) => this.metadata = metadata)
    // this.openApiService.getDimensions(this.sourceId, this.tableId).subscribe((dimensions) => this.dimensions = dimensions)
    // this.openApiService.getFlags(this.sourceId, this.tableId).subscribe((flags) => this.flags = flags)
    // this.openApiService.getQuery(this.sourceId, this.tableId).subscribe((query) => {
    //   this.openApiService.getData(this.sourceId, this.tableId, query).subscribe((data) => this.data = data)
    // })
  }

}

<h1>Sources</h1>
<div *ngFor="let source of sources">
  <li>{{source.title}}</li>
</div>

// Code_samples/React/fhi-open-api-client/src/App.js
import './App.css';
import {useEffect, useState} from "react";
import {getData, getQuery, getSources, getTables} from './api'

function App() {
  const sourceId = 'nokkel';
  const tableId = 1;


  const [sources, setSources] = useState([]);
  const [tables, setTables] = useState([]);
  const [modifiedTables, setModifiedTables] = useState([]);
  const [metadata, setMetadata] = useState([]);
  const [flags, setFlags] = useState([]);
  const [dimensions, setDimensions] = useState([]);
  const [query, setQuery] = useState([]);
  const [data, setData] = useState('');

  useEffect(() => {
    let mounted = true;
    getSources()
      .then(items => {
        if (mounted) {
          setSources(items)
        }
      });
    getTables(sourceId)
      .then(items => {
        if (mounted) {
          setTables(items)
        }
      });
    getQuery(sourceId, tableId)
      .then(response => {
        if (mounted) {
          getData(sourceId, tableId, response)
            .then(response => {
              const subset = `${JSON.stringify(response).substring(0, 1000)}...`
              setData(subset)
            })
          setQuery(response)
        }
      })
    return () => mounted = false;
  }, []);

  return (
    <div className="App">
      <div>
        <h2>Sources</h2>
        <ul>
          {sources.map(item => (<li key={item.title}>{item.title}</li>))}
        </ul>
        <h2>Query</h2>
        <pre>{JSON.stringify(query)}</pre>
        <h2>Data</h2>
        <pre>{data}</pre>
      </div>
    </div>
  );
}

export default App;
